# Hans Maric

## Gephryin
There's like 277 types of gephryn.

- Is the distribution of subtype abundance a fingerprint of some specific
  evolutionary behaviour?

G. creates a hexagonal latice. In terms of affinity: Gly > GABAR > other
channels.


## PSD-95
It has more than 300 PDZ1-2 tandem domains. Moreover, the binding sequence is
highly conserved between SAP97, PSD-93 and PSD-95.
The idea is that we want to produce ligands for these PDZ1-2 and PDZ-3 regions.
I don't quite understand everything, the talk is kind of evaluating how we can
approach this issue?

## Ankyrin
Kind of present everywhere, but less abundant at the spines and the dendrites.
There are 2 independend binding sites, one specialized for ion channels and one
for CAMs (calcium associated molecules?).

**G/B binding site**: The G/B binding site is highly conserved, probably to
allow for a conserved kinase interaction. Nav1.9 seems to be the endogenous
superbinder of the Ankyrin scaffold. 

**Cell Adhesion Molecules**: relies again on the G/B site and requires serine
phosphorylation.

Ankyrin seems to be strongly connected to one of the autism related proteins.
Plugging the antibodies. 

# TT
*Energy dynamics of synapses*

1. A whole lot of appreciation of the experimental possibilities ('the golden
 age of molecular data').
2. The question: what about the general theory? (population level view of
 molecular dynamics)
3. States an actual question to the public, jokingly. This actually regards the
   best prediction of the model. Interestingly, public asks additional specific
   questions, looks like the "initial slides effect" where people are focused bc
   there is a lot of sugar in the medicine. People start making their own model.
4. Now the hypothesis: we think that the features we observe come from energy
   optimization. Public is again asked if they have questions.
5. Explains the model.
6. Tuganir study with huge gradient in half-lives

# Jean-Louis Bessereau
*Specification of postsynaptic identity by extracellular matrix proteins*
Extracellular scaffolders

